---
version: '3.3'
services:
  toskose-manager:
    image: diunipisocc/toskose-manager:latest
    deploy: &id001
      mode: replicated
      replicas: 1
      restart_policy:
        condition: "on-failure"
    environment:
    - HTTP_PORT=10001
    - HTTP_USER=admin
    - HTTP_PASSWORD=admin
    networks: &id002
    - "toskose-network"
    container_name: thinking-toskose-manager
    hostname: thinking-toskose-manager
  maven:
    image: maven:3.3-jdk-8
    deploy: *id001
    environment:
    - SUPERVISORD_HTTP_PORT=9001
    - SUPERVISORD_HTTP_USER=admin
    - SUPERVISORD_HTTP_PASSWORD=admin
    - SUPERVISORD_LOG_LEVEL=INFO
    - INPUT_REPO=https://github.com/jacopogiallo/thoughts-api
    - INPUT_BRANCH=master
    - INPUT_DBURL=mongodb
    - INPUT_DBPORT=27017
    - INPUT_DBNAME=thoughtsSharing
    - INPUT_COLLECTIONNAME=thoughts
    - INPUT_DATA=/toskose/apps/api/artifacts/default_data.csv
    - INPUT_PORT=8080
    networks: *id002
    container_name: thinking-maven
    hostname: thinking-maven
    ports:
    - "8080:8000/tcp"
  node:
    image: node:6
    deploy: *id001
    environment:
    - SUPERVISORD_HTTP_PORT=9002
    - SUPERVISORD_HTTP_USER=admin
    - SUPERVISORD_HTTP_PASSWORD=admin
    - SUPERVISORD_LOG_LEVEL=INFO
    - INPUT_REPO=https://github.com/jacopogiallo/thoughts-gui
    - INPUT_BRANCH=master
    - INPUT_APIURL=localhost
    - INPUT_APIPORT=8000
    - INPUT_APIRESOURCE=thoughts
    networks: *id002
    container_name: thinking-node
    hostname: thinking-node
    ports:
    - "3000:8080/tcp"
  mongodb:
    image: mongo:3.4
    deploy: *id001
    environment:
    - SUPERVISORD_HTTP_PORT=9003
    - SUPERVISORD_HTTP_USER=admin
    - SUPERVISORD_HTTP_PASSWORD=admin
    - SUPERVISORD_LOG_LEVEL=INFO
    networks: *id002
    container_name: thinking-mongodb
    hostname: thinking-mongodb
    volumes:
    - "dbvolume:/data/db"
networks:
  toskose-network:
    driver: "overlay"
    attachable: true
volumes:
  toskose-manager-volume:
  dbvolume:
