version: 2.1
jobs:
  build-and-test:
    working_directory: ~/toskose
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          keys: 
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: install dependencies management (poetry)
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths: 
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: install linter (flak8)
          command: |
            poetry run flake8 .
      - run:
          name: run tests (pytest) and report coverage
          command: | # omitting the dependencies path (no coverage in dependencies)
            poetry run coverage run --omit="/home/circleci/.cache/pypoetry/virtualenvs" -m pytest
  
  deployment:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
        name: Publish to PyPI
        command: | # need to setup envs in CircleCI settings
          poetry publish --build --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" --no-interaction

# when the defined job(s) is ran
workflows:
  version: 2.1

  # everytime a piece of code changes
  build-and-test-workflow:
    jobs:
      - build-and-test
    
  deployment-workflow:
    jobs:

      # build and test just on git tags (GitHub release)
      - build-and-test:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - deployment:
          requires:
            - build-and-test
          filters:
              tags:
                only: /v[0-9]+(\.[0-9]+)*/
              branches:
                ignore: /.*/